name: update activity graph

on:
  # run automatically once a day
  schedule:
    - cron: "0 4 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

permissions:
  contents: write

jobs:
  activity-graph:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: alexcerezo/activity-graph@v1
        with:
          username: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
